In [89]:
import numpy as np
import pandas as pd

In [90]:
df_communes = pd.read_csv("donnees_communes.csv")
df_communes_sorted = df_communes.sort_values(by=['COM'])
df_communes_sorted.reset_index(drop=True, inplace = True)
df_communes_sorted["index"] =  df_communes_sorted.index + 1
df_communes_sorted

,REG,CODREG,COD,CODARR,CODCAN,CODCOM,COM,PMUN,PCAP,PTOT,index
0,Nouvelle-Aquitaine,75,64,3.0,27,1,Aast,186,7,193,1
1,Nouvelle-Aquitaine,44,55,2.0,10,1,Abainville,290,10,300,2
2,Nouvelle-Aquitaine,32,60,1.0,11,1,Abancourt,621,8,629,3
3,Nouvelle-Aquitaine,32,59,2.0,09,1,Abancourt,469,13,482,4
4,Nouvelle-Aquitaine,44,54,3.0,02,1,Abaucourt,296,3,299,5
...,...,...,...,...,...,...,...,...,...,...,...
34986,Bretagne,28,27,3.0,20,230,Ã‰zy-sur-Eure,3702,55,3757,34987
34987,Normandie,44,57,3.0,08,521,Å’ting,2706,53,2759,34988
34988,Nouvelle-Aquitaine,32,62,1.0,38,633,Å’uf-en-Ternois,251,3,254,34989
34989,Hauts-de-France,44,51,2.0,06,410,Å’uilly,652,10,662,34990
34990,Nouvelle-Aquitaine,32,02,2.0,06,565,Å’uilly,291,3,294,34991

In [91]:
df_population = df_communes_sorted[["REG","CODREG","COM","PMUN","PCAP","PTOT"]]
df_population

                      REG  CODREG              COM  PMUN  PCAP  PTOT
0      Nouvelle-Aquitaine      75             Aast   186     7   193
1      Nouvelle-Aquitaine      44       Abainville   290    10   300
2      Nouvelle-Aquitaine      32        Abancourt   621     8   629
3      Nouvelle-Aquitaine      32        Abancourt   469    13   482
4      Nouvelle-Aquitaine      44        Abaucourt   296     3   299
...                   ...     ...              ...   ...   ...   ...
34986            Bretagne      28    Ã‰zy-sur-Eure  3702    55  3757
34987           Normandie      44           Å’ting  2706    53  2759
34988  Nouvelle-Aquitaine      32  Å’uf-en-Ternois   251     3   254
34989     Hauts-de-France      44          Å’uilly   652    10   662
34990  Nouvelle-Aquitaine      32          Å’uilly   291     3   294

[34991 rows x 6 columns]

In [92]:
df_geographie = pd.read_csv("geographie.csv")
df_geographie_sorted = df_geographie.sort_values(by=['com_nom_maj_court'])
df_geographie_sorted.reset_index(drop=True, inplace = True)
df_geographie_sorted["index"] =  df_geographie_sorted.index + 1
df_geographie_sorted

,regrgp_nom,reg_nom,reg_nom_old,aca_nom,dep_nom,com_code,com_code1,com_code2,com_id,com_nom_maj_court,...,fr_id,fe_id,uu_id_99,au_code,au_id,auc_id,auc_nom,uu_id_10,geolocalisation,index
0,Province,Nouvelle-Aquitaine,Aquitaine,Bordeaux,PyrÃ©nÃ©es-Atlantiques,64001,64001,64001,C64001,AAST,...,FR11,FE1,SO,NaN,AU997,C64001,Aast,SO,"43.2908772184,-0.0817726913902",1
1,Province,Grand Est,Lorraine,Nancy-Metz,Meuse,55001,55001,55001,C55001,ABAINVILLE,...,FR11,FE1,SO,NaN,AU000,C55001,Abainville,SO,"48.5326982449,5.51524727317",2
2,Province,Hauts-de-France,Picardie,Amiens,Oise,60001,60001,60001,C60001,ABANCOURT,...,FR11,FE1,SO,NaN,AU998,C60001,Abancourt,SO,"49.6930546611,1.76924374516",3
3,Province,Hauts-de-France,Nord-Pas-de-Calais,Lille,Nord,59001,59001,59001,C59001,ABANCOURT,...,FR11,FE1,SO,123,AU123,AU123,Cambrai,SO,"50.2368696873,3.20731301738",4
4,Province,Grand Est,Lorraine,Nancy-Metz,Meuse,55002,55002,55002,C55002,ABAUCOURT HAUTECOURT,...,FR11,FE1,SO,NaN,AU998,C55002,Abaucourt-Hautecourt,SO,"49.1969606553,5.54868808043",5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
38911,Province,Hauts-de-France,Nord-Pas-de-Calais,Lille,Pas-de-Calais,62905,62905,62905,C62905,ZUDAUSQUES,...,FR11,FE1,SO,99,AU099,AU099,Saint-Omer,SO,"50.7526605163,2.16024730203",38912
38912,Province,Hauts-de-France,Nord-Pas-de-Calais,Lille,Pas-de-Calais,62906,62906,62906,C62906,ZUTKERQUE,...,FR11,FE1,SO,NaN,AU997,C62906,Zutkerque,UU62205,"50.8528869572,2.05960239074",38913
38913,Province,Grand Est,Alsace,Strasbourg,Bas-Rhin,67562,67562,67562,C67562,ZUTZENDORF,...,FR11,FE1,SO,SO,SO,SO,SO,SO,NaN,38914
38914,Province,Hauts-de-France,Nord-Pas-de-Calais,Lille,Nord,59668,59668,59668,C59668,ZUYDCOOTE,...,FR11,FE1,UU59206,38,AU038,AU038,Dunkerque,UU59137,"51.06377209,2.48763279882",38915
38915,Province,Hauts-de-France,Nord-Pas-de-Calais,Lille,Nord,59669,59669,59669,C59669,ZUYTPEENE,...,FR11,FE1,SO,NaN,AU997,C59669,Zuytpeene,SO,"50.7918240712,2.42330162819",38916

In [93]:
df_geographie = df_geographie[["reg_nom","dep_nom","com_code","com_nom_maj_court"]]
df_region = df_geographie[["reg_nom","dep_nom","com_code","com_nom_maj_court"]]

In [94]:
df_valeur_fonciere = pd.read_csv("valeur_fonciere.csv", low_memory=False)
df_valeur_fonciere
df_code_postal = df_valeur_fonciere[["Commune","Code postal"]]
df_code_postal = df_code_postal.drop_duplicates(subset=['Commune'])
df_code_postal = df_code_postal.sort_values(by=['Commune'])
df_code_postal.reset_index(drop=True, inplace = True)
df_code_postal["index"] =  df_code_postal.index + 1
df_code_postal

KeyError: "None of [Index(['Commune', 'Code postal'], dtype='object')] are in the [columns]"

In [ ]:
df_region = df_region.drop_duplicates(subset=['reg_nom'])
df_region.reset_index(drop=True, inplace = True)
df_region["id_reg"] = df_region.index + 1
df_region = df_region[["id_reg","reg_nom"]]
df_region.to_csv("region.csv")

In [ ]:
df_dep = df_geographie
df_dep = df_region.merge(df_dep)
df_dep = df_dep.drop_duplicates(subset=['dep_nom'])
df_dep.reset_index(drop=True, inplace = True)
df_dep["dep_code"] = df_dep.index + 1
df_dep = df_region.merge(df_dep)
df_dep = df_dep[["id_reg","dep_nom","dep_code"]]
df_dep.to_csv("dep.csv")
df_dep

In [ ]:
df_communes = df_geographie_sorted.merge(df_communes_sorted)
df_communes = df_communes[['reg_nom','dep_nom','com_code','com_nom_maj_court']]
df_communes = df_communes.merge(df_region)
df_communes = df_communes.merge(df_dep)
df_communes= df_communes[["dep_code",'com_code','com_nom_maj_court']]
df_communes =df_communes.rename(columns={"dep_code": "code_departement", "com_code": "code_commune", "com_nom_maj_court" : "Commune"})
df_communes = pd.merge(df_communes, df_code_postal, how="outer", on=["Commune"])
df_communes.drop_duplicates("Commune", inplace = True)
df_communes = df_communes.sort_values(by=['Commune'])
df_communes = df_communes =df_communes.rename(columns={"Commune" : "nom_commune"})

df_communes.drop(columns = "index",inplace = True)
df_communes.reset_index(drop=True, inplace = True)
df_communes["id_codedep_codecommune"] = df_communes.index + 1
df_communes.to_csv("communes.csv")
df_communes

In [ ]:
df_population = df_communes_sorted
df_population.drop_duplicates("COM",inplace = True)
df_population = df_population[["PMUN","PCAP","PTOT"]]
df_population.reset_index(drop=True, inplace = True)
df_population["id_codedep_codecommune"] = df_population.index + 1
df_population = pd.merge(df_communes, df_population, how="inner", on=["id_codedep_codecommune"])
df_population = df_population[["id_codedep_codecommune","PMUN","PCAP","PTOT"]]
df_population.to_csv("population.csv")

In [ ]:
df_valeur_fonciere = df_valeur_fonciere[["No voie","Code postal", "Type de voie", "Voie", 
                                        "Nombre pieces principales", "Surface reelle bati","Surface Carrez du 1er lot",
                                       "Type local"]]
df_valeur_fonciere.rename(columns = {"No voie" : "no_voie", "Type de voie" : "type_voie", "Voie" : "voie",
                        "Nombre pieces principales" : "total_piece", "Surface reelle bati": "surface_carrez",
                         "Surface Carrez du 1er lot" : "surface_local", "Type local": "type_local"}, inplace = True)

In [ ]:
df_valeur_fonciere["index"] = df_valeur_fonciere.index + 1
df_valeur_fonciere

In [ ]:
df_valeur_fonciere
df_valeur_fonciere = pd.merge(df_valeur_fonciere, df_communes, how="inner", on=["Code postal"])
df_valeur_fonciere

In [ ]:
df_valeur_fonciere.drop_duplicates("index",inplace = True)
df_valeur_fonciere

In [ ]:
df_valeur_fonciere = df_valeur_fonciere[["no_voie","type_voie","voie","total_piece","surface_carrez","surface_local","type_local",
                                        "id_codedep_codecommune"]]

df_valeur_fonciere.reset_index(drop=True, inplace = True)
df_valeur_fonciere["id_bien"] = df_valeur_fonciere.index + 1
df_valeur_fonciere.to_csv("valeur_fonciere.csv")
df_valeur_fonciere

In [ ]:
from sqlalchemy import create_engine

In [ ]:
engine = create_engine('sqlite://',
                       echo = False)

In [96]:
df_region.to_sql('region_d',
               con = engine)
print(engine.execute("SELECT * FROM 
                     
                     ").fetchall())

OperationalError: (sqlite3.OperationalError) no such table: Employee_Data
[SQL: SELECT * FROM Employee_Data]
(Background on this error at: https://sqlalche.me/e/14/e3q8)